"""Memory provider catalog helpers."""

from __future__ import annotations

MEMORY_PROVIDER_OPTIONS = {
    "honcho": {
        "label": "Honcho",
        "storage": "cloud/self-hosted",
        "dependencies": [{"kind": "python", "name": "honcho"}],
        "config_files": ["honcho.json"],
        "required_any": [["apiKey", "baseUrl"]],
        "required_fields": ["peerName", "workspace", "aiPeer"],
        "fields": [
            {
                "name": "apiKey",
                "label": "API key",
                "storage": "json",
                "path": "honcho.json",
                "secret": True,
                "help": "Honcho Cloud key from app.honcho.dev.",
            },
            {
                "name": "baseUrl",
                "label": "Self-hosted base URL",
                "storage": "json",
                "path": "honcho.json",
                "secret": False,
                "help": "Use this instead of an API key for a self-hosted Honcho instance.",
            },
            {
                "name": "peerName",
                "label": "User peer",
                "storage": "json",
                "path": "honcho.json",
                "secret": False,
                "help": "Human peer identity shared across Hermes profiles.",
            },
            {
                "name": "workspace",
                "label": "Workspace",
                "storage": "json",
                "path": "honcho.json",
                "secret": False,
                "help": "Shared Honcho workspace.",
            },
            {
                "name": "aiPeer",
                "label": "AI peer",
                "storage": "json",
                "path": "honcho.json",
                "secret": False,
                "help": "AI peer identity for this Hermes profile.",
            },
        ],
        "modes": [
            {
                "id": "cloud",
                "label": "Cloud",
                "storage": "cloud",
                "description": "Honcho Cloud using an app.honcho.dev API key.",
                "fields": ["apiKey", "peerName", "workspace", "aiPeer"],
                "required_fields": ["apiKey", "peerName", "workspace", "aiPeer"],
                "required_any": [],
                "optional_fields": [],
            },
            {
                "id": "self_hosted",
                "label": "Self-hosted",
                "storage": "self-hosted",
                "description": "Self-hosted Honcho using a base URL.",
                "fields": ["baseUrl", "peerName", "workspace", "aiPeer"],
                "required_fields": ["baseUrl", "peerName", "workspace", "aiPeer"],
                "required_any": [],
                "optional_fields": [],
            },
        ],
        "setup_command": "hermes memory setup",
        "config_command": "hermes config set memory.provider honcho",
    },
    "openviking": {
        "label": "OpenViking",
        "storage": "self-hosted",
        "dependencies": [
            {"kind": "python", "name": "openviking"},
            {"kind": "command", "name": "openviking-server"},
        ],
        "required_fields": ["OPENVIKING_ENDPOINT"],
        "required_env": ["OPENVIKING_ENDPOINT"],
        "config_files": [".env"],
        "fields": [
            {
                "name": "OPENVIKING_ENDPOINT",
                "label": "Endpoint",
                "storage": "env",
                "secret": False,
                "help": "Running OpenViking server, for example http://localhost:1933.",
            },
            {
                "name": "OPENVIKING_API_KEY",
                "label": "API key",
                "storage": "env",
                "secret": True,
                "help": "Only needed for authenticated OpenViking servers.",
            },
            {
                "name": "OPENVIKING_AGENT",
                "label": "Agent ID",
                "storage": "env",
                "secret": False,
                "help": "Hermes peer ID for peer-scoped memories.",
            },
            {
                "name": "OPENVIKING_ACCOUNT",
                "label": "Account",
                "storage": "env",
                "secret": False,
                "help": "Optional local/trusted-mode account.",
            },
            {
                "name": "OPENVIKING_USER",
                "label": "User",
                "storage": "env",
                "secret": False,
                "help": "Optional local/trusted-mode user.",
            },
        ],
        "modes": [
            {
                "id": "self_hosted",
                "label": "Self-hosted",
                "storage": "self-hosted",
                "description": "Running OpenViking server endpoint.",
                "fields": [
                    "OPENVIKING_ENDPOINT",
                    "OPENVIKING_API_KEY",
                    "OPENVIKING_AGENT",
                    "OPENVIKING_ACCOUNT",
                    "OPENVIKING_USER",
                ],
                "required_fields": ["OPENVIKING_ENDPOINT"],
                "required_any": [],
                "optional_fields": [
                    "OPENVIKING_API_KEY",
                    "OPENVIKING_AGENT",
                    "OPENVIKING_ACCOUNT",
                    "OPENVIKING_USER",
                ],
            },
        ],
        "setup_command": "hermes memory setup",
        "config_command": "hermes config set memory.provider openviking",
    },
    "mem0": {
        "label": "Mem0",
        "storage": "cloud/self-hosted",
        "dependencies": [{"kind": "python", "name": "mem0"}],
        "required_any": [["MEM0_API_KEY", "mode"]],
        "required_env": ["MEM0_API_KEY"],
        "config_files": [".env", "mem0.json"],
        "fields": [
            {
                "name": "MEM0_API_KEY",
                "label": "API key",
                "storage": "env",
                "secret": True,
                "help": "Mem0 Platform key. OSS mode can be configured through hermes memory setup.",
            },
            {
                "name": "mode",
                "label": "Mode",
                "storage": "json",
                "path": "mem0.json",
                "secret": False,
                "help": "platform or oss.",
            },
            {
                "name": "user_id",
                "label": "User ID",
                "storage": "json",
                "path": "mem0.json",
                "secret": False,
                "help": "Mem0 user identifier.",
            },
            {
                "name": "agent_id",
                "label": "Agent ID",
                "storage": "json",
                "path": "mem0.json",
                "secret": False,
                "help": "Mem0 agent identifier.",
            },
            {
                "name": "rerank",
                "label": "Rerank",
                "storage": "json",
                "path": "mem0.json",
                "secret": False,
                "help": "true or false; platform mode only.",
            },
        ],
        "modes": [
            {
                "id": "platform",
                "label": "Cloud Platform",
                "storage": "cloud",
                "description": "Mem0 Platform using an API key.",
                "fields": ["MEM0_API_KEY", "mode", "user_id", "agent_id", "rerank"],
                "required_fields": ["MEM0_API_KEY"],
                "required_any": [],
                "optional_fields": ["user_id", "agent_id", "rerank"],
            },
            {
                "id": "oss",
                "label": "OSS / self-hosted",
                "storage": "self-hosted",
                "description": "Mem0 OSS configured through local settings.",
                "fields": ["mode", "user_id", "agent_id"],
                "required_fields": ["mode"],
                "required_any": [],
                "optional_fields": ["user_id", "agent_id"],
            },
        ],
        "setup_command": "hermes memory setup",
        "config_command": "hermes config set memory.provider mem0",
    },
    "hindsight": {
        "label": "Hindsight",
        "storage": "cloud/local",
        "dependencies": [{"kind": "python", "name": "hindsight"}],
        "required_any": [["HINDSIGHT_API_KEY", "mode"]],
        "required_env": ["HINDSIGHT_API_KEY"],
        "config_files": [".env", "hindsight/config.json"],
        "fields": [
            {
                "name": "HINDSIGHT_API_KEY",
                "label": "API key",
                "storage": "env",
                "secret": True,
                "help": "Hindsight Cloud key. Local mode can use provider-specific LLM keys.",
            },
            {
                "name": "mode",
                "label": "Mode",
                "storage": "json",
                "path": "hindsight/config.json",
                "secret": False,
                "help": "cloud or local.",
            },
            {
                "name": "bank_id",
                "label": "Bank ID",
                "storage": "json",
                "path": "hindsight/config.json",
                "secret": False,
                "help": "Memory bank identifier.",
            },
            {
                "name": "recall_budget",
                "label": "Recall budget",
                "storage": "json",
                "path": "hindsight/config.json",
                "secret": False,
                "help": "low, mid, or high.",
            },
            {
                "name": "memory_mode",
                "label": "Memory mode",
                "storage": "json",
                "path": "hindsight/config.json",
                "secret": False,
                "help": "hybrid, context, or tools.",
            },
        ],
        "modes": [
            {
                "id": "cloud",
                "label": "Cloud",
                "storage": "cloud",
                "description": "Hindsight Cloud using an API key.",
                "fields": ["HINDSIGHT_API_KEY", "mode", "bank_id", "recall_budget", "memory_mode"],
                "required_fields": ["HINDSIGHT_API_KEY"],
                "required_any": [],
                "optional_fields": ["bank_id", "recall_budget", "memory_mode"],
            },
            {
                "id": "local",
                "label": "Local",
                "storage": "local",
                "description": "Local Hindsight memory bank.",
                "fields": ["mode", "bank_id", "recall_budget", "memory_mode"],
                "required_fields": ["mode"],
                "required_any": [],
                "optional_fields": ["bank_id", "recall_budget", "memory_mode"],
            },
        ],
        "setup_command": "hermes memory setup",
        "config_command": "hermes config set memory.provider hindsight",
    },
    "holographic": {
        "label": "Holographic",
        "storage": "local",
        "dependencies": [],
        "required_fields": [],
        "config_files": ["config.yaml"],
        "fields": [
            {
                "name": "db_path",
                "label": "SQLite DB path",
                "storage": "yaml",
                "section": ["plugins", "hermes-memory-store"],
                "secret": False,
                "help": "Defaults to $HERMES_HOME/memory_store.db.",
            },
            {
                "name": "auto_extract",
                "label": "Auto extract",
                "storage": "yaml",
                "section": ["plugins", "hermes-memory-store"],
                "secret": False,
                "help": "true or false.",
            },
            {
                "name": "default_trust",
                "label": "Default trust",
                "storage": "yaml",
                "section": ["plugins", "hermes-memory-store"],
                "secret": False,
                "help": "0.0 to 1.0.",
            },
        ],
        "modes": [
            {
                "id": "local",
                "label": "Local",
                "storage": "local",
                "description": "Local SQLite-backed memory store.",
                "fields": ["db_path", "auto_extract", "default_trust"],
                "required_fields": [],
                "required_any": [],
                "optional_fields": ["db_path", "auto_extract", "default_trust"],
            },
        ],
        "setup_command": "hermes memory setup",
        "config_command": "hermes config set memory.provider holographic",
    },
    "retaindb": {
        "label": "RetainDB",
        "storage": "cloud",
        "dependencies": [{"kind": "python", "name": "requests"}],
        "required_fields": ["RETAINDB_API_KEY"],
        "required_env": ["RETAINDB_API_KEY"],
        "config_files": [".env"],
        "fields": [
            {
                "name": "RETAINDB_API_KEY",
                "label": "API key",
                "storage": "env",
                "secret": True,
                "help": "RetainDB account key.",
            },
        ],
        "modes": [
            {
                "id": "cloud",
                "label": "Cloud",
                "storage": "cloud",
                "description": "RetainDB Cloud using an API key.",
                "fields": ["RETAINDB_API_KEY"],
                "required_fields": ["RETAINDB_API_KEY"],
                "required_any": [],
                "optional_fields": [],
            },
        ],
        "setup_command": "hermes memory setup",
        "config_command": "hermes config set memory.provider retaindb",
    },
    "byterover": {
        "label": "ByteRover",
        "storage": "local/cloud",
        "dependencies": [{"kind": "command", "name": "brv"}],
        "required_fields": [],
        "config_files": ["byterover/"],
        "fields": [],
        "modes": [
            {
                "id": "local",
                "label": "Local / CLI",
                "storage": "local/cloud",
                "description": "ByteRover configuration is handled by the brv CLI.",
                "fields": [],
                "required_fields": [],
                "required_any": [],
                "optional_fields": [],
            },
        ],
        "setup_command": "hermes memory setup",
        "config_command": "hermes config set memory.provider byterover",
    },
    "supermemory": {
        "label": "Supermemory",
        "storage": "cloud",
        "dependencies": [{"kind": "python", "name": "supermemory"}],
        "required_fields": ["SUPERMEMORY_API_KEY"],
        "required_env": ["SUPERMEMORY_API_KEY"],
        "config_files": [".env", "supermemory.json"],
        "fields": [
            {
                "name": "SUPERMEMORY_API_KEY",
                "label": "API key",
                "storage": "env",
                "secret": True,
                "help": "Supermemory Cloud API key.",
            },
            {
                "name": "SUPERMEMORY_CONTAINER_TAG",
                "label": "Container override",
                "storage": "env",
                "secret": False,
                "help": "Optional override for the configured container tag.",
            },
            {
                "name": "container_tag",
                "label": "Container tag",
                "storage": "json",
                "path": "supermemory.json",
                "secret": False,
                "help": "Supports {identity} for profile-scoped containers.",
            },
            {
                "name": "max_recall_results",
                "label": "Max recall results",
                "storage": "json",
                "path": "supermemory.json",
                "secret": False,
                "help": "Number of recalled items to format into context.",
            },
            {
                "name": "search_mode",
                "label": "Search mode",
                "storage": "json",
                "path": "supermemory.json",
                "secret": False,
                "help": "hybrid, memories, or documents.",
            },
        ],
        "modes": [
            {
                "id": "cloud",
                "label": "Cloud",
                "storage": "cloud",
                "description": "Supermemory Cloud using an API key.",
                "fields": [
                    "SUPERMEMORY_API_KEY",
                    "SUPERMEMORY_CONTAINER_TAG",
                    "container_tag",
                    "max_recall_results",
                    "search_mode",
                ],
                "required_fields": ["SUPERMEMORY_API_KEY"],
                "required_any": [],
                "optional_fields": [
                    "SUPERMEMORY_CONTAINER_TAG",
                    "container_tag",
                    "max_recall_results",
                    "search_mode",
                ],
            },
        ],
        "setup_command": "hermes memory setup",
        "config_command": "hermes config set memory.provider supermemory",
    },
    "memori": {
        "label": "Memori",
        "storage": "cloud",
        "dependencies": [
            {"kind": "python", "name": "hermes_memori"},
            {"kind": "command", "name": "hermes-memori"},
        ],
        "required_fields": [],
        "config_files": [],
        "fields": [],
        "modes": [
            {
                "id": "cloud",
                "label": "Cloud / bridge",
                "storage": "cloud",
                "description": "Memori bridge configuration is handled by hermes-memori.",
                "fields": [],
                "required_fields": [],
                "required_any": [],
                "optional_fields": [],
            },
        ],
        "setup_command": "hermes memory setup",
        "config_command": "hermes config set memory.provider memori",
        "notes": [
            "Install with: pip install hermes-memori",
            "Run: hermes-memori install",
            "Then run: hermes memory setup",
        ],
    },
    "cognee": {
        "label": "Cognee",
        "storage": "local/docker/mcp",
        "dependencies": [
            {"kind": "python", "name": "cognee"},
            {"kind": "command", "name": "cognee-cli"},
        ],
        "required_fields": [],
        "config_files": [".env", "cognee.json"],
        "fields": [
            {
                "name": "LLM_API_KEY",
                "label": "LLM API key",
                "storage": "env",
                "secret": True,
                "help": "Required for local Cognee Python/CLI memory pipelines.",
            },
            {
                "name": "COGNEE_API_URL",
                "label": "API URL",
                "storage": "env",
                "secret": False,
                "help": "Cognee API server URL, for example http://localhost:8000.",
            },
            {
                "name": "COGNEE_MCP_URL",
                "label": "MCP URL",
                "storage": "env",
                "secret": False,
                "help": "Cognee MCP HTTP/SSE endpoint, for example http://localhost:8001.",
            },
            {
                "name": "COGNEE_DATASET",
                "label": "Dataset",
                "storage": "json",
                "path": "cognee.json",
                "secret": False,
                "help": "Dataset name used for Hermes memory.",
            },
        ],
        "modes": [
            {
                "id": "python_cli",
                "label": "Python / CLI",
                "storage": "local",
                "description": "Local Cognee package and cognee-cli.",
                "fields": ["LLM_API_KEY", "COGNEE_DATASET"],
                "required_fields": ["LLM_API_KEY"],
                "required_any": [],
                "optional_fields": ["COGNEE_DATASET"],
            },
            {
                "id": "docker_api",
                "label": "Docker API",
                "storage": "self-hosted",
                "description": "Cognee API server, usually exposed on localhost:8000.",
                "fields": ["COGNEE_API_URL", "COGNEE_DATASET"],
                "required_fields": ["COGNEE_API_URL"],
                "required_any": [],
                "optional_fields": ["COGNEE_DATASET"],
            },
            {
                "id": "mcp_http",
                "label": "MCP HTTP",
                "storage": "mcp",
                "description": "Cognee MCP server, usually exposed on localhost:8001.",
                "fields": ["COGNEE_MCP_URL", "COGNEE_DATASET"],
                "required_fields": ["COGNEE_MCP_URL"],
                "required_any": [],
                "optional_fields": ["COGNEE_DATASET"],
            },
        ],
        "setup_command": "uv pip install cognee && cognee-cli -ui",
        "config_command": "hermes config set memory.provider cognee",
        "notes": [
            "Docker API commonly uses port 8000.",
            "MCP server commonly uses port 8001.",
        ],
    },
    "agentmemory": {
        "label": "agentmemory",
        "storage": "local/server/mcp",
        "dependencies": [
            {"kind": "command", "name": "agentmemory"},
            {"kind": "command", "name": "npx"},
        ],
        "required_fields": [],
        "config_files": [".env", "agentmemory.json"],
        "fields": [
            {
                "name": "AGENTMEMORY_URL",
                "label": "Server URL",
                "storage": "env",
                "secret": False,
                "help": "agentmemory server URL, usually http://localhost:3111.",
            },
            {
                "name": "AGENTMEMORY_SECRET",
                "label": "Secret",
                "storage": "env",
                "secret": True,
                "help": "Optional shared secret for protected agentmemory servers.",
            },
            {
                "name": "AGENTMEMORY_MCP_COMMAND",
                "label": "MCP command",
                "storage": "json",
                "path": "agentmemory.json",
                "secret": False,
                "help": "Default: npx -y @agentmemory/mcp.",
            },
        ],
        "modes": [
            {
                "id": "rest_server",
                "label": "REST server",
                "storage": "local",
                "description": "Local or remote agentmemory server.",
                "fields": ["AGENTMEMORY_URL", "AGENTMEMORY_SECRET"],
                "required_fields": ["AGENTMEMORY_URL"],
                "required_any": [],
                "optional_fields": ["AGENTMEMORY_SECRET"],
            },
            {
                "id": "mcp_server",
                "label": "MCP server",
                "storage": "mcp",
                "description": "MCP shim command used by Hermes.",
                "fields": ["AGENTMEMORY_MCP_COMMAND", "AGENTMEMORY_URL", "AGENTMEMORY_SECRET"],
                "required_fields": ["AGENTMEMORY_MCP_COMMAND"],
                "required_any": [],
                "optional_fields": ["AGENTMEMORY_URL", "AGENTMEMORY_SECRET"],
            },
        ],
        "setup_command": "npm install -g @agentmemory/agentmemory && agentmemory",
        "config_command": "hermes config set memory.provider agentmemory",
        "notes": [
            "Default REST server: http://localhost:3111.",
            "Default MCP command: npx -y @agentmemory/mcp.",
        ],
    },
    "memos": {
        "label": "MemOS",
        "storage": "cloud/self-hosted",
        "dependencies": [{"kind": "python", "name": "memos"}],
        "required_fields": [],
        "config_files": [".env", "memos.json"],
        "fields": [
            {
                "name": "MEMOS_API_KEY",
                "label": "API key",
                "storage": "env",
                "secret": True,
                "help": "MemOS Cloud API key.",
            },
            {
                "name": "MEMOS_BASE_URL",
                "label": "Base URL",
                "storage": "env",
                "secret": False,
                "help": "Self-hosted MemOS API URL.",
            },
            {
                "name": "MOS_CHAT_MODEL_PROVIDER",
                "label": "Model provider",
                "storage": "env",
                "secret": False,
                "help": "openai, azure, qwen, deepseek, minimax, ollama, huggingface, or vllm.",
            },
            {
                "name": "MEMOS_NAMESPACE",
                "label": "Namespace",
                "storage": "json",
                "path": "memos.json",
                "secret": False,
                "help": "Hermes memory namespace or user scope.",
            },
        ],
        "modes": [
            {
                "id": "cloud",
                "label": "Cloud API",
                "storage": "cloud",
                "description": "Hosted MemOS Cloud API.",
                "fields": ["MEMOS_API_KEY", "MEMOS_NAMESPACE"],
                "required_fields": ["MEMOS_API_KEY"],
                "required_any": [],
                "optional_fields": ["MEMOS_NAMESPACE"],
            },
            {
                "id": "self_hosted",
                "label": "Self-hosted",
                "storage": "self-hosted",
                "description": "Private MemOS deployment.",
                "fields": ["MEMOS_BASE_URL", "MOS_CHAT_MODEL_PROVIDER", "MEMOS_NAMESPACE"],
                "required_fields": ["MEMOS_BASE_URL"],
                "required_any": [],
                "optional_fields": ["MOS_CHAT_MODEL_PROVIDER", "MEMOS_NAMESPACE"],
            },
        ],
        "setup_command": "git clone https://github.com/MemTensor/MemOS.git && cd MemOS && pip install -r ./docker/requirements.txt",
        "config_command": "hermes config set memory.provider memos",
        "notes": [
            "Cloud API and self-hosted deployments use different required fields.",
            "Self-hosted MemOS model provider is selected with MOS_CHAT_MODEL_PROVIDER.",
        ],
    },
}

MEMORY_PROVIDER_CAPABILITIES = {
    "honcho": {
        "external_read": True,
        "external_read_mode": "provider_specific",
        "direct_hud_config": True,
        "requires_network": True,
        "local_storage": False,
        "supports_tools": True,
        "supports_auto_recall": True,
        "supports_session_ingest": True,
        "supports_manual_write": True,
        "hooks": ["prefetch", "queue_prefetch", "on_session_end", "tools"],
    },
    "openviking": {
        "external_read": True,
        "external_read_mode": "provider_specific",
        "direct_hud_config": True,
        "requires_network": True,
        "local_storage": False,
        "supports_tools": True,
        "supports_auto_recall": True,
        "supports_session_ingest": True,
        "supports_manual_write": True,
        "hooks": ["prefetch", "queue_prefetch", "on_session_end", "tools"],
    },
    "mem0": {
        "external_read": True,
        "external_read_mode": "provider_specific",
        "direct_hud_config": True,
        "requires_network": True,
        "local_storage": False,
        "supports_tools": True,
        "supports_auto_recall": True,
        "supports_session_ingest": False,
        "supports_manual_write": True,
        "hooks": ["prefetch", "tools"],
    },
    "hindsight": {
        "external_read": True,
        "external_read_mode": "provider_specific",
        "direct_hud_config": True,
        "requires_network": True,
        "local_storage": False,
        "supports_tools": True,
        "supports_auto_recall": True,
        "supports_session_ingest": True,
        "supports_manual_write": True,
        "hooks": ["prefetch", "queue_prefetch", "on_session_end", "tools"],
    },
    "holographic": {
        "external_read": True,
        "external_read_mode": "local_sqlite",
        "direct_hud_config": True,
        "requires_network": False,
        "local_storage": True,
        "supports_tools": True,
        "supports_auto_recall": True,
        "supports_session_ingest": True,
        "supports_manual_write": True,
        "hooks": ["prefetch", "on_session_end", "tools"],
    },
    "retaindb": {
        "external_read": True,
        "external_read_mode": "provider_specific",
        "direct_hud_config": True,
        "requires_network": True,
        "local_storage": False,
        "supports_tools": True,
        "supports_auto_recall": True,
        "supports_session_ingest": False,
        "supports_manual_write": True,
        "hooks": ["prefetch", "queue_prefetch", "tools"],
    },
    "byterover": {
        "external_read": False,
        "external_read_mode": "none",
        "direct_hud_config": False,
        "requires_network": False,
        "local_storage": True,
        "supports_tools": True,
        "supports_auto_recall": True,
        "supports_session_ingest": False,
        "supports_manual_write": True,
        "hooks": ["prefetch", "queue_prefetch", "on_pre_compress", "tools"],
    },
    "supermemory": {
        "external_read": True,
        "external_read_mode": "provider_specific",
        "direct_hud_config": True,
        "requires_network": True,
        "local_storage": False,
        "supports_tools": True,
        "supports_auto_recall": True,
        "supports_session_ingest": True,
        "supports_manual_write": True,
        "hooks": ["prefetch", "on_session_end", "tools"],
    },
    "memori": {
        "external_read": False,
        "external_read_mode": "none",
        "direct_hud_config": False,
        "requires_network": True,
        "local_storage": False,
        "supports_tools": True,
        "supports_auto_recall": False,
        "supports_session_ingest": True,
        "supports_manual_write": False,
        "hooks": ["tools"],
    },
    "cognee": {
        "external_read": True,
        "external_read_mode": "provider_summary",
        "direct_hud_config": True,
        "requires_network": False,
        "local_storage": True,
        "supports_tools": True,
        "supports_auto_recall": True,
        "supports_session_ingest": True,
        "supports_manual_write": True,
        "hooks": ["mcp", "tools", "session_ingest"],
    },
    "agentmemory": {
        "external_read": True,
        "external_read_mode": "provider_summary",
        "direct_hud_config": True,
        "requires_network": False,
        "local_storage": True,
        "supports_tools": True,
        "supports_auto_recall": True,
        "supports_session_ingest": True,
        "supports_manual_write": True,
        "hooks": ["mcp", "rest", "session_start", "pre_compact", "tools"],
    },
    "memos": {
        "external_read": True,
        "external_read_mode": "provider_summary",
        "direct_hud_config": True,
        "requires_network": True,
        "local_storage": True,
        "supports_tools": True,
        "supports_auto_recall": True,
        "supports_session_ingest": True,
        "supports_manual_write": True,
        "hooks": ["mcp", "api", "session_ingest"],
    },
}

OFFICIAL_SCHEMA_PROVIDERS = {
    "honcho",
    "openviking",
    "mem0",
    "hindsight",
    "holographic",
    "retaindb",
    "supermemory",
}

OFFICIAL_PROVIDER_GROUP = "official"
COMMUNITY_PROVIDER_GROUP = "community"

COMMUNITY_SCHEMA_PROVIDERS = {
    "cognee",
    "agentmemory",
    "memos",
}


def provider_group(provider: str) -> str:
    """Return the display group for a memory provider."""
    return (
        COMMUNITY_PROVIDER_GROUP
        if provider in COMMUNITY_SCHEMA_PROVIDERS
        else OFFICIAL_PROVIDER_GROUP
    )
